### ISSUE TITLE
Editor Color Scheme Plugin

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-jetbrains-editor#28]
JetBrains announced a new feature for the platform that allows to [export editor color schemes as plugins][ref-blog] which can be easily installed from the [Plugin Repository][plug-repo]. Color scheme plugins can be filtered with the [*Editor Color Schemes*][plug-repo-cs-cat] category.

This feature greatly improves the installation process for Nord regarding the UX and version update handling compared to the manual installation and will be the recommended method.

### Tasks

* [x] Create a exported color scheme `.jar` plugin for already released- and future versions
* [x] Update the documentation
* [x] Upload the plugin to the [Plugin Repository][plug-repo] including the plugin documentation, screenshots and changelogs / release notes

[ref-blog]: https://blog.jetbrains.com/platform/2017/12/export-intellij-editor-themes-as-plugins
[plug-repo]: https://plugins.jetbrains.com
[plug-repo-cs-cat]: https://plugins.jetbrains.com/tag?headline=151-editor-color-schemes
