### ISSUE TITLE
Rename project to "Nord JetBrains Editor"

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-jetbrains-editor#31]
The project started with the main indention in my mind to target the [IntelliJ IDEA][ref-iji] IDE and create a new port project for each IDE from JetBrains, but since all these awesome products are internally based on the IntelliJ engine the color scheme format can be used universally.

To clarify the compatibility with all IDEs from JetBrains the project should be renamed to *Nord JetBrains Editor* (`nord-jetbrains-editor`). The "Editor" post-fix word is used to keep the namespace open for the possibility that JetBrains introduces a official UI theme API someday. This is currently only possible by using an unoffical way like overriding internal IDE files as shown by the [Material Theme UI][ref-plug-mat-ui] plugin.

### Tasks

* [x] Replace the project name in all documentations
* [x] Rename all affected project files
* [x] Update the documentation assets like the *README* logo banner
* [x] Update the project logo banner in the main [Nord][nord-gh-ijis-banner] repository
  :arrow_right: arcticicestudio/nord#69

[ref-iji]: https://www.jetbrains.com/idea
[ref-plug-mat-ui]: https://plugins.jetbrains.com/plugin/8006-material-theme-ui
[nord-gh-ijis-banner]: https://github.com/arcticicestudio/nord/blob/develop/src/assets/nord-intellij-idea-syntax-banner.ai
